server:
  port: 8084

spring:
  application:
    name: election-service

  datasource:
    url: jdbc:postgresql://localhost:5432/vote_electiondb
    username: postgres
    password: kigali45
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE